[project]
name = "dashboard-streamlit"
version = "0.1.0"
description = "Dashoard de Vendas com Streamlit"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "plotly>=6.4.0",
    "streamlit>=1.51.0",
]
